### PR TITLE
feat(general/restrict-prioriy-classes): add a policy to allow for the restriction of priority classes.

### PR DESCRIPTION
**Pull request by justbert**

### CODE REVIEW

**Review by MichaelPatsula — DISMISSED** [review]
LGTM! 😄 

The only thought I have is in the src.rego should the Kubernetes object that is being validated be tested to make sure the kind = pod just in case the constraint match.kinds is configured incorrectly, or do you think it is unnecessary?

Also it looks like the PR title is being cut off. To be able to identify the PR in the future, I am thinking maybe it should of shortened to something like feat(general): add new restrict-priority-class policy.

**Comment by justbert** [comment]
Thanks for the review, @MichaelPatsula! I think it's a good thought but in this case it should be unnecessary since the policy will fail if there is nothing defined in the `priorityClassName` field. I added a [test](https://github.com/StatCan/gatekeeper-policies/pull/51/commits/6390851f166486a2ea63d25b195620ffcb4a1bd0) to validate that. :)

**Comment by justbert** [comment]
I also added an extra comment on the rego to help explicitly explain what the policy should run against.

**Review by MichaelPatsula — APPROVED** [review]
Excellent, that makes sense to me! 

Small reminder, do you think the the PR title should be shortened so there isn't parts cut off?

**Pull request merged**
