### PR TITLE
feat(secured-gateways): policy that ensures Gateways are configured t…

### PR DESCRIPTION
**Pull request by justbert**
…o align to ITSP.40.062.

A couple of questions:
- Are there other things we should be validating such as the tls.mode?
- Should we add an exclusion list for exceptions?

### CODE REVIEW

**Comment by justbert** [comment]
Also, @zachomedia, this is my first Rego, so this might be totally wrong...

**Comment by zachomedia** [comment]
@justbert That's looking pretty good to me!

**Comment by justbert** [comment]
Thanks! It works (now)!
I wish we it was easier to keep the policy external to the template for testing, though. There's no way to import the contents of a file into a field via kustomize. We'd need to build a CI to generate the templates after the fact, but it might be a good way to get some testing into here.

**Comment by sylus** [comment]
I merged this awesome work and also integrated the additional testing.

@zachomedia was nice enough to take a look as well. 

Committed with proper attribution since had to make some minor adjustments.

**Pull request closed without merging**
