### PR TITLE
feat: Add restrict-hostnames constraint template

### PR DESCRIPTION
**Pull request by zachomedia**
This constraint template is part of the proposal on restricting specific hostnames. This cannot be merged until the proposal is accepted by the Technical Advisory Group (TAG).

### CODE REVIEW

**Comment by zachomedia** [comment]
@justbert My initial thought is we would, at least initially, list 1-1 what paths would end up in the ingress / virtual service objects. I'm not against changing that mindset if there's a use case or a good reason to do otherwise.

**Comment by justbert** [comment]
I had a suggestion that I left on the CNPEP:

I think we should build an accompanying policy that enforces the structure of the annotation to ensure that the data is always correct. In this way, we can ensure that the policy can always be functioning. 

What do you think?

**Review by mohameddahrouj — APPROVED** [review]

**Comment by justbert** [comment]
Do you know why the tests are failing @sylus? The policies deploy fine in local testing.

**Comment by zachomedia** [comment]
@justbert I got it to pass. After debugging the workflow locally, it turns out the version of Gatekeeper we were installing the CI did not have a version of OPA with the `json.is_valid` function. I updated Gatekeeper to the latest and it looks to be happy now.

**Comment by justbert** [comment]
Thanks! Good catch! I'll check our internal versions versus what's being installed here and make the necessary tickets.

**Comment by sylus** [comment]
Hi @zachomedia great job can u just update the README.md before we merge?

**Comment by justbert** [comment]
> Hi @zachomedia great job can u just update the README.md before we merge?

@sylus - It was discussed this morning. There's still more to happen before this can be merged, however, since the _ ingress-hostnames-conflict_ needs to be added to this Policy.

**Comment by justbert** [comment]
How do you want us to go about indicating if a Policy is deprecated, @sylus? Is that even something we want to indicate?

**Comment by justbert** [comment]
> @justbert we can make a deprecated folder and move it there and remove the rule from kustomize so not installed by default.

@sylus - Will do!

**Comment by justbert** [comment]
Superseded by #38

**Comment by frazs** [comment]
Reopening, I had merged into this branch instead of master 😀

**Pull request merged**
